### ISSUE TITLE
version 0.2.0 or 0.2.1?

### ISSUE THREAD

**Issue by Bibi56** [mojodna/tilelive-xray#4]
Is the current version 0.2.0? The version we get through npm install -g tilelive-xray looks different, but is named 0.2.0 too.

```
npm ls -g tilelive-xray
/usr/local/lib
└── tilelive-xray@0.2.0
```

In /usr/local/lib/node_modules/tilelive-xray/index.js I see the good old hard-coded definition of XRay.registerProtocols:

```
XRay.registerProtocols = function(tilelive) {
  // TODO iterate over previously registered protocols and prepend this?
  tilelive.protocols[PREFIX + "http:"] = this;
```

...

**Comment by sethfitz** [comment]
Looks like I never published @JesseCrocker's changes (I think I was waiting on a minor version bump to `tilelive-modules`, which has happened).

0.3.0 is now current.

Thanks for the heads-up!

**Comment by Bibi56** [comment]
Thanks for the amazing responsiveness!
